gpu=$1
echo "export CUDA_VISIBLE_DEVICES=$gpu"
export CUDA_VISIBLE_DEVICES=${gpu}
train_batch=$2
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets mnli --data_dir data/canonical_data/bert-base-cased --force
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets rte --data_dir data/canonical_data/bert-base-cased --force
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets qqp --data_dir data/canonical_data/bert-base-cased --force
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets qnli --data_dir data/canonical_data/bert-base-cased --force
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets mrpc --data_dir data/canonical_data/bert-base-cased --force
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets sst --data_dir data/canonical_data/bert-base-cased --force
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets cola --data_dir data/canonical_data/bert-base-cased --force
python task_level_matrix_tune.py --batch_size ${train_batch} --batch_size_eval 1 --init_checkpoint bert-base-cased --bert_model_type bert-base-cased --encoder_type 1 --num_hidden_layers 12 --answer_opt 1 --optimizer adamax --train_datasets wnli --data_dir data/canonical_data/bert-base-cased --force
# python calculate_corr.py --bert_model_type bert-base-cased --task_list mnli,rte,qqp,qnli,mrpc,sst,cola,wnli
